### ISSUE TITLE
invizio:ImgAlgo:0.1.0 is not a public artifact

### ISSUE THREAD

**Issue by holgerbrandl** [benoalo/CIP#1]
`mvn package` just reports
```
The POM for invizio:ImgAlgo:jar:0.1.0 is missing, no dependency information available
```

**Comment by benoalo** [comment]
Hi @holgerbrandl,
Thanks for the feedback, at the moment ImgAlgo can be found [there](https://github.com/benoitlo/ImgAlgo).
You can run maven install on ImgAlgo then it will be visible on you local installation to compile CIP.
